version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ETH_HTTP_URL=${ETH_HTTP_URL}
      - MONGO_URL=${MONGO_URL}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data

volumes:
  mongo_data:
  redis_data: