version: "3.9"
services:
  adapter:
    build: .
    image: gcr.io/tracer-external-adapters/cryptopunks
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - ETH_HTTP_URL=${ETH_HTTP_URL}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    restart: always
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data

volumes:
  mongo_data:
  redis_data: